version: '3.9'

services:
  conduktor:
    image: conduktor/conduktor-platform:latest
    container_name: conduktor
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 2G  # Максимальный лимит памяти
        reservations:
          memory: 1G  # Минимальный резерв памяти