server:
  port: 8081
spring:
  application:
    name: solo-leveling-task
  elasticsearch:
    uris: http://${SERVER_HOST}:9200
  kafka:
    bootstrap-servers: ${SERVER_HOST}:9092
    properties:
      schema.registry.url: http://${SERVER_HOST}:8081
